spring.application.name=ceox-data-service

server.port=8081
firebase.config.path=classpath:firebase/agencyx-fb-service-account.json
ceox.intelligent.url=http://localhost:8082
firebase.storage.bucket=maenagencydev.firebasestorage.app